### ISSUE TITLE
Problem s prenasanim EAN / ID

### ISSUE THREAD

**Issue by gurudlan** [superfaktura/presta#1]
Zdravim,

po update mi neprenasa do faktury EAN ale ID...potrebujem EAN, poradite mi prosim kde by som to v kode zmenil?

Dakujem

**Comment by superfaktura** [comment]
Ak som správne pochopil tak vy potrebujete preniest EAN ako SKU položky ? 
Momentálne je tam takáto logika  najskôr sa modul pozerá na  product_reference ak je prázdne na product_upc a následne product_ean13 .

Táto logika setovania sa nachádza v superfaktura.php na riadkoch 692 až 695

**Comment by gurudlan** [comment]
ano tak ste pochopil spravne.
tak teda toto by mohlo ist:
```
 //$sku = $product['product_reference'];
            
//if(empty($sku)){ $sku = $product['product_upc']; }
            
//if(empty($sku)){ $sku = $product['product_ean13']; }
            
//if(empty($sku)){ $sku = null; }
            
$sku = $product['product_ean13'];
```

rovno by to malo hodit EAN, tak ci?

**Comment by superfaktura** [comment]
áno rovno Vám to hodí EAN  ale pre Vaše dobro by som si tam hodil podmienku ak je ean prazdne nech sa  sku nastavi na null
